#simplified version of mongo creation with mongo express
# oc process -f mongo-template.yaml -p user=root -p password=password

apiVersion: v1
kind: Template
metadata:
  name: mongodb-template
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mongo-express
      app.kubernetes.io/component: mongo-express
      app.kubernetes.io/instance: mongo-express
    name: mongo-express
  spec:
    port:
      targetPort: 8081-tcp
    to:
      kind: ""
      name: mongo-express
      weight: null

- apiVersion: v1
  kind: Service
  metadata:
    name: mongo-express
    labels:
      app: mongo-express
  spec:
    ports:
    - port: 8081
      name: mongo-express
    clusterIP: None
    selector:
      app: mongodb
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: mongo-express
    name: mongo-express
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongo-express
    strategy: {}
    template:
      metadata:
        labels:
          app: mongo-express
      spec:
        containers:
        - image: mongo-express
          name: mongo-express
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: ${user}
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: ${password}
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      app: mongodb
  spec:
    ports:
    - port: 27017
      name: mongodb
    clusterIP: None
    selector:
      app: mongodb
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongodb
  spec:
    serviceName: "mongodb"
    selector:
      matchLabels:
        app: mongodb
    replicas: 1
    template:
      metadata:
        labels:
          app: mongodb
      spec:
        containers:
          - name: mongodb
            image: mongo
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: ${user}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: ${password}
            ports:
              - containerPort: 27017
            volumeMounts:
            - name: mongodb
              mountPath: /data/db
    volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

parameters:
- description: Username for root user
  value: 'root'
  name: user
- description: Password used for Redis authentication
  value: 'password'
  name: password
